### ISSUE TITLE
Appswitcher: Create thumbnails only once on start. 

### ISSUE THREAD

**Issue by arpio23** [cutie-shell/cutie-home#3] opened 2024-03-09 14:21 UTC
Get the thumbnails only once when starting the appswitcher. It works fine rn, but if you have more apps open, it creates a very high cpu load due to screencopy constantly updating thumbnails.

We could also consider to update them every 3 seconds or something?

**Comment by erikinkinen** [comment] 2024-03-18 18:04
This should be resolvable without changing behaviour. Essentially, sending the buffer to cutie-home should be a similar load to the client sending to the compositor.

We just need to figure ou why the screencopy is so CPU intensive as it really should not.

Additionally, I see artefacts on the thumbnails once in a while.

**Comment by arpio23** [comment] 2024-03-19 22:08
Yeah, the artifacts are with any transparent window, basically only cutie, with every redraw. The easiest way to see it, start cutie-terminal and run htop, open appswitcher. As you should see, the artifacts are gone after few redraws and the cycle keeps ongoing.

**Comment by erikinkinen** [comment] 2024-06-11 15:53
The artifacts are now fixed in cutie-wlc. I cannot reproduce the aforementioned CPU stress either. Having seven applications open on sargo did not cause significantly more CPU load than one application. As of now, the thumbnails are updated on [thumbnail_damage](https://github.com/cutie-shell/cutie-wlc/blob/cutie/src/protocols/cutie-shell-private.xml#L54) event. 

Unless there are further concerns on your mind, @arpio23, I think this should be closed.

**Closed as not planned** 2024-06-11 16:03 UTC
Labels: enhancement
